name: Firebase CD

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '15.x'
    secrets:
      FIREBASE_TOKEN:
        required: true

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ inputs.node-version }}
      - run: yarn
      - run: yarn build && yarn next export
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
