name: Firebase CD

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      FIREBASE_TOKEN:
        required: true

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '15.x'
      - run: yarn
      - run: yarn next build && yarn next export
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
